Updated isort validation step

diff --git a/.github/workflows/BlackFormat.yml b/.github/workflows/BlackFormat.yml
--- a/.github/workflows/BlackFormat.yml
+++ b/.github/workflows/BlackFormat.yml
@@ -21,26 +21,17 @@ jobs:
       - name: Setup Isort
         run: python3 -m pip install isort
       - name: Validate Isort Formatting
+        run: python3 ./exporter/SynthesisFusionAddin/tools/verifyIsortFormatting.py
+        id: isort-format-validation
+        continue-on-error: true
+      - name: Check Isort Formatting Validation
         run: |
-          python - <<'EOF'
-          import os, subprocess, sys
-
-          EXPORTER_DIR = "exporter/SynthesisFusionAddin"
-          files = (lambda d: [os.path.abspath(os.path.join(root, filename)) for root, _, filenames in os.walk(d)
-                   for filename in filenames if filename.endswith(".py")])(EXPORTER_DIR)
-          oldFileStates = [open(file, "r").readlines() for file in files]
-          subprocess.call(["isort", EXPORTER_DIR], bufsize=1, shell=False)
-          newFileStates = [open(file, "r").readlines() for file in files]
-          exitCode = 0
-          for i, (oldFileState, newFileState) in enumerate(zip(oldFileStates, newFileStates)):
-            for j, (previousLine, newLine) in enumerate(zip(oldFileState, newFileState)):
-              if previousLine != newLine:
-                print(f"File {files[i]} is not formatted correctly!\nLine: {j + 1}")
-                exitCode = 1
-
-          if not exitCode: print("All files are formatted correctly with isort!")
-          sys.exit(exitCode)
-          EOF
+          if [ ${{ steps.format-validation.outcome }} == "success" ]; then
+            echo "Isort Formatting Validation Passed"
+          else
+            echo "Isort Formatting Validation Failed"
+            exit 1
+          fi
       - name: Validate Black Formatting
         uses: psf/black@stable
         with:
