refactor(maybe): update workflows

diff --git a/.github/workflows/FissionBuild.yml b/.github/workflows/FissionBuild.yml
--- a/.github/workflows/FissionBuild.yml
+++ b/.github/workflows/FissionBuild.yml
@@ -3,7 +3,7 @@ name: Fission - Build
 on:
   workflow_dispatch: {}
   pull_request:
-    branches: [ prod, dev ]
+    branches: [prod, dev]
 
 jobs:
   buildFission:
@@ -21,7 +21,7 @@ jobs:
         uses: actions/cache@v3
         with:
           key: "${{runner.os}}-npm-fission-${{hashFiles('fission/package.json')}}"
-          path: 'fission/node_modules'
+          path: "fission/node_modules"
           restore-keys: |
             ${{runner.os}}-npm-fission-
             ${{runner.os}}-npm
@@ -29,9 +29,9 @@ jobs:
       - name: Install Dependencies
         run: |
           cd fission
-          npm install
+          bun install
 
       - name: Build Fission
         run: |
           cd fission
-          npm run build && echo "Build Passed" || (echo "Build Failed" && exit 1)
+          bun run build && echo "Build Passed" || (echo "Build Failed" && exit 1)
